remote_theme: fuelclock/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Goud Graaiers Info]
description: [The complete information on everything about our guild!]
